### ISSUE TITLE
REPL History is not persisted

### ISSUE THREAD

**Issue by deepal** [deepal/baapan#5]
After v2.x.x, baapan does not keep REPL history across sessions anymore. It is required to find a way to write history manually to `~/.node_repl_history

Reference: https://nodejs.org/api/repl.html#repl_persistent_history

**Comment by dpjayasekara** [comment]
This is a common issue with custom REPLs and a potential solution is mentioned here: https://medium.com/@tjwebb/a-custom-node-repl-with-history-is-not-as-hard-as-it-looks-3eb2ca7ec0bd
