### ISSUE TITLE
Support top level REPL await

### ISSUE THREAD

**Issue by deepal** [deepal/baapan#6]
Top level await is not supported since v2.x.x as Baapan is now implemented using `repl` module instead of a dynamically required module similar to `node --require baapan`. 

Due to this, using `--experimental-repl-await` is not possible anymore in order to facilitate top level REPL await.

**Comment by shahidcodes** [comment]
I was able to do it with some hack. Will create PR once my pending one is closed/merged.
![image](https://user-images.githubusercontent.com/17620737/72368654-8781c300-3724-11ea-8b6b-f622c591e1a4.png)

**Comment by deepal** [comment]
Thanks @shahidcodes for this! Will look into the previous PR asap.
